<script lang="ts">
	const depts = [
		["AIP", "Academic Internship Program"],
		["AASM", "African American Studies Minor"],
		["AWP", "Analytical Writing Program"],
		["ANTH", "Anthropology"],
		["AUDL", "Audiology"],
		["BIOI", "Bioinformatics"],
		["BIOL", "Biological Sciences, School of"],
		["BIOM", "Biomedical Sciences"],
		["CHEM", "Chemistry and Biochemistry"],
		["CHIN", "Chinese Studies"],
		["CLAS", "Classical Studies"],
		["CCS", "Climate Change Studies"],
		["CSP", "Climate Science and Policy"],
		["CLIN", "Clinical Psychology"],
		["CLRE", "Clinical Research"],
		["COGS", "Cognitive Science"],
		["COMM", "Communication"],
		["CSS", "Computational Social Science"],
		["CONT", "Contemporary Issues"],
		["CGS", "Critical Gender Studies"],
		["CAT", "Culture, Art, and Technology"],
		["DSC", "Data Science"],
		["DSGN", "Design"],
		["DOC", "Dimensions of Culture"],
		["ECON", "Economics"],
		["EDS", "Education Studies Program"],
		["ERC", "Eleanor Roosevelt College"],
		["ENG", "Engineering, Jacobs School of"],
		["BENG", "Bioengineering"],
		["CSE", "Computer Science and Engineering (CSE)"],
		["ECE", "Electrical and Computer Engineering (ECE)"],
		["MAS", "Master of Advanced Studies (MAS)\u00a0in Engineering"],
		["MAE", "Mechanical and Aerospace Engineering (MAE)"],
		["MAE-AESE", "Mechanical and Aerospace Engineering (MAE)"],
		["NANO", "NanoEngineering (NANO)"],
		["SE", "Structural Engineering"],
		["ENVR", "Environmental Studies"],
		["ESYS", "Environmental Systems"],
		["ETHN", "Ethnic Studies"],
		["FILM", "Film Studies"],
		["GLBH", "Global Health Program"],
		["GPS", "School of Global Policy and Strategy (GPS)"],
		["GSS", "Global South Studies"],
		["LHCO", "Health Care\u2014Leadership of Healthcare Organizations"],
		["HIST", "History"],
		["HDS", "Human Developmental Sciences Program"],
		["HMNR", "Human Rights and Migration Minor"],
		["HUM", "Humanities"],
		["INTL", "International Studies"],
		["JAPN", "Japanese Studies"],
		["JWSP", "Jewish Studies"],
		["LATI", "Latin American Studies"],
		["LAWS", "Law and Society"],
		["LING", "Linguistics"],
		["LIT", "Literature"],
		["MMW", "The Making of the Modern World"],
		["MGT", "Rady School of Management"],
		["MBC", "Marine Biodiversity and Conservation"],
		["MATS", "Materials Science and Engineering Program"],
		["MATH", "Mathematics"],
		["MSED", "Mathematics and Science Education"],
		["MCWP", "Muir College"],
		["MUS", "Music"],
		["NEU", "Neurosciences"],
		["PHIL", "Philosophy"],
		["PHYS", "Physics"],
		["POLI", "Political Science"],
		["PSYC", "Psychology"],
		["FMPH", "Public Health"],
		["RELI", "Religion, Study of"],
		["REV", "Revelle College"],
		["SCIS", "Science Studies"],
		["SIO", "Scripps Institution of Oceanography"],
		["SEV", "Seventh College"],
		["SXTH", "Sixth College"],
		["SOC", "Sociology"],
		["SYN", "Synthesis Program"],
		["THEA", "Theatre and Dance"],
		["TMC", "Thurgood Marshall College"],
		["USP", "Urban Studies and Planning"],
		["VIS", "Visual Arts"],
		["WARR", "Warren College"]
	];
</script>

<h1 class="text-gray-600 underline underline-offset-[10px] decoration-gray-700/50 font-extrabold text-center uppercase text-4xl leading-relaxed tracking-wider">UCSD Course Catalog</h1>

<ul class="grid mt-8 gap-1 grid-cols-1 sm:grid-cols-2 p-4 border border-gray-700 text-gray-400 text-lg rounded-lg">
	{#each depts as [abbr, name]}
		<li>
			<a href="/{abbr}" class="hover:underline hover:underline-offset-2">{name}</a>
		</li>
	{/each}
</ul>
